function surfpower(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 08-Dec-2015 10:38:08

% Create figure
figure1 = figure;
colormap('hot');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1580 1590]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-2.65 3]);
view(axes1,[0.5 90]);
grid(axes1,'on');
hold(axes1,'on');
    xlim([1580 1590])
    ylim([-2.65 3])
% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceColor','interp',...
    'EdgeColor','none');

% Create xlabel
xlabel('\lambda [nm]');

% Create ylabel
ylabel('\phi^{(2)} [ps^2]');

% Create colorbar
colorbar('peer',axes1);

