function createfigureSPP(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 22-Sep-2015 18:26:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.141843971631206 0.609583333333333 0.783156028368794],...
    'LineWidth',2,...
    'FontSize',14);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-6 6]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.4 1.8001]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','\phi_{NL0}=');
set(plot1(2),'DisplayName','\phi_{NL0}=');
set(plot1(3),'DisplayName','\phi_{NL0}=');
set(plot1(4),'DisplayName','\phi_{NL0}=');
set(plot1(5),'DisplayName','\phi_{NL0}=');
set(plot1(6),'DisplayName','\phi_{NL0}=');
set(plot1(7),'DisplayName','\phi_{NL0}=');

% Create xlabel
xlabel({'\phi^{(2)} [ps^{2}]'},'FontSize',14);

% Create ylabel
ylabel({'Normalized SPP'},'FontSize',14);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.78536882063254 0.365528728945035 0.180677540777917 0.551615445232467],...
    'LineWidth',2);

